### ISSUE TITLE
🐛Cant create build (editor namespace errors)

### ISSUE THREAD

**Issue by davey2206** [Rogue-Ape-Studios/Crusader#134]
![Image](https://github.com/Rogue-Ape-Studios/Crusader/assets/39116329/7de2962d-2974-40dc-a1eb-ce81c547d538)

**Comment by NathanThus** [comment]
@davey2206 I'm going to need a bit more to go on, as a quick test did not reveal any errors on my end. Reloading the file, forcing a recompilation also created no results.

**Comment by NathanThus** [comment]
Found the bug, and I believe I might have a really simple fix for it.
