### ISSUE TITLE
🐛 Infinite health regeneration

### ISSUE THREAD

**Issue by Timsel1** [Rogue-Ape-Studios/Crusader#161]
After getting hit and the regeneration starting, when getting hit again during this the regeneration never stops and becomes faster. Even when the can regenerate bool is turned off, the player still regenerates health.

![Image](https://github.com/Rogue-Ape-Studios/Crusader/assets/90602424/de6b62af-f3a8-450a-a462-eb76f21b8fc4)

**Comment by NathanThus** [comment]
@Timsel1 This bug seems to have been fixed, as I am perfectly capable of dying. Shall we close the issue?

**Comment by NathanThus** [comment]
Confirmed via other channels, issue is closed.
