### ISSUE TITLE
♻️ Separate `Health` into `EnemyHealth` and `PlayerHealth`

### ISSUE THREAD

**Issue by NathanThus** [Rogue-Ape-Studios/Crusader#187]
**Is your feature request related to a problem? Please describe.**
The Enemies should not need a scriptable object to tell them it's properties, while due to the persistent nature of the player, it is highly recommended.

**Describe the solution you'd like**
Create two seperate implementations of the health script, with slightly different properties. The player health uses scriptable objects, while the enemy health should be easily tweakable within the editor. This makes it easier for designers to make changes.

**Describe alternatives you've considered**
Keeping it as is, and using scriptable objects. Though this obfuscates the properties.

**Additional context**
I'd like everyones thoughts on this.
@davey2206 @Timsel1 @429277 @AoSkye29

**Comment by davey2206** [comment]
yea I do think 2 scripts one for player and one for enemies would be better. this will also help with creating status effects for the enemies. you could still have a scriptableobject to get the starting stats for an enemy but you could also simply still do this within the prefab.
