### ISSUE TITLE
♻️ Overhaul Ability System

### ISSUE THREAD

**Issue by NathanThus** [Rogue-Ape-Studios/Crusader#191]
Before anyone works on this, please submit a class diagram, and propsed system for implementation.

**Comment by NathanThus** [comment]
@davey2206 Post dragons den item maybe?

**Comment by davey2206** [comment]
Yes most likely post dragons den. still need to think about a good solution

**Comment by NathanThus** [comment]
# Proposal
![image](https://github.com/Rogue-Ape-Studios/Crusader/assets/99728206/ee642eb6-cda1-4bbd-bca6-022b607758a8)

**Comment by NathanThus** [comment]
To-Do List

- [x] ✅ Validate Class Diagram
- [ ] ✨ Implement Base Classes
- [ ] ✨ Create Combat Classes
- [ ] ✨ Create Support Classes
- [ ] ✨ Add Support for Player Damage Scaling

**Comment by NathanThus** [comment]
# Final version - Approved
![Ability Design](https://github.com/Rogue-Ape-Studios/Crusader/assets/99728206/1c3f6fa5-e18c-4442-ac8c-028d47da3afd)

**Comment by NathanThus** [comment]
Editor scripting for visualisation purposes.
